#!/bin/bash
echo "Enter The Login Name:"
read username
echo "Enter The Password:"
read password

if [[ $username == "root"  && $password == "root123" ]]
then
  echo -e "You're Logged In\n"
elif [ $username != "user" ]
then
  echo -e "Invalid User Name\n"
else
  echo -e "Invalid Password\n"
fi

# Read the ServerNames from Properties file
for server in `cat /tmp/suri `
do
        # Printing the ServerName
#       echo "Processing ServerName "$server
        echo -n "Processing ServerName: "
        read server
        echo Your Processing ServerName $server


#        # Write some Shell Script for Temporary Usage and Save in Current location
#        cat << 'EOF' > ./TestScript.sh
#               #!/bin/bash
#               echo "My Name is $0"
#               echo "I am Running on `hostname`"
#               echo "The Date on the Current System is `date`"
#               echo "That's all!!. I am Exitting"
#               exit 0
#EOF
#       chmod a+x TestScript.sh

        # SCP - copy the script file from Current Directory to Remote Server
#       sshpass -p$pass scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no TestScript.sh $user@$server:/tmp/TestScript.sh

        # Take Rest for 5 Seconds
#        sleep 5

        # SSH to remote Server  and Execute a Command [ Invoke the Script ]
#        sshpass -p$pass ssh   -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $user@$server "/tmp/TestScript.sh"
#        sshpass -p$pass ssh   -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $user@$server
          sshpass -p$password ssh $username@$server
exit 1
done

